-- =====================================================
-- ADMIN-USER PRIVATE MESSAGING SYSTEM
-- Migration: Add private chat functionality between admins and users
-- Created: 2025-01-14
-- =====================================================

-- =====================================================
-- 1. CREATE TABLES
-- =====================================================

-- Conversations table to track chat threads between admins and users
CREATE TABLE IF NOT EXISTS "public"."conversations" (
    "id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    "admin_id" uuid NOT NULL REFERENCES "public"."profiles"("id") ON DELETE CASCADE,
    "user_id" uuid NOT NULL REFERENCES "public"."profiles"("id") ON DELETE CASCADE,
    "last_message_at" timestamp with time zone DEFAULT timezone('utc', now()),
    "last_message_preview" text,
    "is_archived" boolean DEFAULT false,
    "archived_by" uuid REFERENCES "public"."profiles"("id") ON DELETE SET NULL,
    "created_at" timestamp with time zone DEFAULT timezone('utc', now()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT timezone('utc', now()) NOT NULL,
    UNIQUE(admin_id, user_id)
);

COMMENT ON TABLE "public"."conversations" IS 'Tracks private conversation threads between admins and users';
COMMENT ON COLUMN "public"."conversations"."admin_id" IS 'Admin participant in the conversation';
COMMENT ON COLUMN "public"."conversations"."user_id" IS 'User participant in the conversation';
COMMENT ON COLUMN "public"."conversations"."last_message_preview" IS 'Preview of the last message for quick viewing';

-- Messages table for private admin-user chats
CREATE TABLE IF NOT EXISTS "public"."admin_messages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "conversation_id" uuid NOT NULL REFERENCES "public"."conversations"("id") ON DELETE CASCADE,
    "sender_id" uuid NOT NULL REFERENCES "public"."profiles"("id") ON DELETE CASCADE,
    "recipient_id" uuid NOT NULL REFERENCES "public"."profiles"("id") ON DELETE CASCADE,
    "content" text NOT NULL,
    "is_read" boolean DEFAULT false,
    "read_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT timezone('utc', now()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT timezone('utc', now()) NOT NULL,
    CONSTRAINT "admin_messages_content_check" CHECK (length(content) > 0 AND length(content) <= 5000)
);

COMMENT ON TABLE "public"."admin_messages" IS 'Stores private messages between admins and users';
COMMENT ON COLUMN "public"."admin_messages"."conversation_id" IS 'References the conversation this message belongs to';
COMMENT ON COLUMN "public"."admin_messages"."is_read" IS 'Whether the recipient has read this message';

-- =====================================================
-- 2. CREATE INDEXES FOR PERFORMANCE
-- =====================================================

CREATE INDEX "idx_conversations_admin_id" ON "public"."conversations" ("admin_id");
CREATE INDEX "idx_conversations_user_id" ON "public"."conversations" ("user_id");
CREATE INDEX "idx_conversations_last_message_at" ON "public"."conversations" ("last_message_at" DESC);
CREATE INDEX "idx_conversations_archived" ON "public"."conversations" ("is_archived");

CREATE INDEX "idx_admin_messages_conversation_id" ON "public"."admin_messages" ("conversation_id");
CREATE INDEX "idx_admin_messages_sender_id" ON "public"."admin_messages" ("sender_id");
CREATE INDEX "idx_admin_messages_recipient_id" ON "public"."admin_messages" ("recipient_id");
CREATE INDEX "idx_admin_messages_created_at" ON "public"."admin_messages" ("created_at" DESC);
CREATE INDEX "idx_admin_messages_is_read" ON "public"."admin_messages" ("recipient_id", "is_read") WHERE is_read = false;

-- =====================================================
-- 3. CREATE FUNCTIONS AND TRIGGERS
-- =====================================================

-- Function to update conversation's last_message_at and preview
CREATE OR REPLACE FUNCTION "public"."update_conversation_on_message"()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
    UPDATE conversations
    SET 
        last_message_at = NEW.created_at,
        last_message_preview = CASE 
            WHEN length(NEW.content) > 100 THEN substring(NEW.content from 1 for 100) || '...'
            ELSE NEW.content
        END,
        updated_at = timezone('utc', now())
    WHERE id = NEW.conversation_id;
    
    RETURN NEW;
END;
$$;

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION "public"."update_admin_messages_updated_at"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = timezone('utc', now());
    RETURN NEW;
END;
$$;

-- Function to update conversations updated_at timestamp
CREATE OR REPLACE FUNCTION "public"."update_conversations_updated_at"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = timezone('utc', now());
    RETURN NEW;
END;
$$;

-- Create triggers
CREATE TRIGGER "trigger_update_conversation_on_message"
    AFTER INSERT ON "public"."admin_messages"
    FOR EACH ROW
    EXECUTE FUNCTION "public"."update_conversation_on_message"();

CREATE TRIGGER "trigger_admin_messages_updated_at"
    BEFORE UPDATE ON "public"."admin_messages"
    FOR EACH ROW
    EXECUTE FUNCTION "public"."update_admin_messages_updated_at"();

CREATE TRIGGER "trigger_conversations_updated_at"
    BEFORE UPDATE ON "public"."conversations"
    FOR EACH ROW
    EXECUTE FUNCTION "public"."update_conversations_updated_at"();

-- =====================================================
-- 4. ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================

ALTER TABLE "public"."admin_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."conversations" ENABLE ROW LEVEL SECURITY;

-- Conversations Policies
-- Users and admins can view conversations they're part of
CREATE POLICY "Users can view their conversations"
    ON "public"."conversations"
    FOR SELECT
    USING (
        auth.uid() = admin_id OR auth.uid() = user_id
    );

-- Only admins can create conversations
CREATE POLICY "Admins can create conversations"
    ON "public"."conversations"
    FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE id = auth.uid() AND role IN ('admin', 'super_admin')
        )
        AND auth.uid() = admin_id
    );

-- Participants can update conversations (archive, etc.)
CREATE POLICY "Participants can update conversations"
    ON "public"."conversations"
    FOR UPDATE
    USING (
        auth.uid() = admin_id OR auth.uid() = user_id
    )
    WITH CHECK (
        auth.uid() = admin_id OR auth.uid() = user_id
    );

-- Admin Messages Policies
-- Users can view messages in their conversations
CREATE POLICY "Users can view their messages"
    ON "public"."admin_messages"
    FOR SELECT
    USING (
        auth.uid() = sender_id OR auth.uid() = recipient_id
    );

-- Users can send messages in their conversations
CREATE POLICY "Users can send messages"
    ON "public"."admin_messages"
    FOR INSERT
    WITH CHECK (
        auth.uid() = sender_id
        AND (
            -- User sending to admin in an existing conversation
            EXISTS (
                SELECT 1 FROM conversations
                WHERE id = conversation_id
                AND (
                    (user_id = auth.uid() AND admin_id = recipient_id)
                    OR (admin_id = auth.uid() AND user_id = recipient_id)
                )
            )
        )
        AND (
            -- Verify recipient is admin OR sender is admin
            EXISTS (
                SELECT 1 FROM profiles
                WHERE id = recipient_id AND role IN ('admin', 'super_admin')
            )
            OR EXISTS (
                SELECT 1 FROM profiles
                WHERE id = auth.uid() AND role IN ('admin', 'super_admin')
            )
        )
    );

-- Recipients can update messages (mark as read)
CREATE POLICY "Recipients can mark messages as read"
    ON "public"."admin_messages"
    FOR UPDATE
    USING (
        auth.uid() = recipient_id
    )
    WITH CHECK (
        auth.uid() = recipient_id
    );

-- Optional: Allow senders to delete their own messages within a time window
CREATE POLICY "Senders can delete recent messages"
    ON "public"."admin_messages"
    FOR DELETE
    USING (
        auth.uid() = sender_id
        AND created_at > (now() - interval '5 minutes')
    );

-- =====================================================
-- 5. GRANT PERMISSIONS
-- =====================================================

GRANT ALL ON TABLE "public"."conversations" TO "anon";
GRANT ALL ON TABLE "public"."conversations" TO "authenticated";
GRANT ALL ON TABLE "public"."conversations" TO "service_role";

GRANT ALL ON TABLE "public"."admin_messages" TO "anon";
GRANT ALL ON TABLE "public"."admin_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."admin_messages" TO "service_role";

GRANT ALL ON SEQUENCE "public"."admin_messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."admin_messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."admin_messages_id_seq" TO "service_role";

-- =====================================================
-- 6. ENABLE REALTIME
-- =====================================================

-- Enable realtime for messages (for instant chat updates)
ALTER PUBLICATION supabase_realtime ADD TABLE admin_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE conversations;

-- =====================================================
-- MIGRATION COMPLETE
-- =====================================================
